name: Passwall
description: PassWall Mobile is a mobile client for PassWall API written with Flutter.
version: 0.3.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  esys_flutter_share:
  path_provider:
  file_picker: # TODO: https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#--desktop-go-flutter
  link:
  flutter_launcher_name:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

flutter_launcher_name:
  name: "PassWall"