name: Passwall
description: PassWall Mobile is a mobile client for PassWall API written with Flutter.
version: 0.5.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http:
  shared_preferences:
  esys_flutter_share:
  path_provider:
  file_picker: # TODO: https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#--desktop-go-flutter
  link:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_name:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - lang/tr.json
    - lang/en.json
    - assets/
  fonts:
    - family: mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
    - family: serif
      fonts:
        - asset: fonts/PlayfairDisplay.ttf

flutter_launcher_name:
  name: "PassWall"

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon.png"