name: macOS Builder

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      #- name: Flutter action
      #  uses: subosito/flutter-action@v1.3.0

      - name: Flutter Master Clone
        run: git clone -b master https://github.com/flutter/flutter.git

      - name: Getting Packs
        run: ./flutter/bin/flutter pub get

      - name: Flutter Config
        run: ./flutter/bin/flutter config --enable-macos-desktop


      #      # Build APK
      #      - name: Build APK
      #        run: ./flutter/bin/flutter build apk
      #
      #      - name: Upload files to a GitHub release
      #        uses: svenstaro/upload-release-action@1.0.1
      #        with:
      #          repo_token: ${{ secrets.GITHUB_TOKEN }}
      #          file: build/app/outputs/apk/release/app-release.apk
      #          asset_name: app-release.apk
      #          tag: v0.5.3
      #          overwrite: true
      #
      #      # apk-arm
      #      - name: Build APK android-arm
      #        run: ./flutter/bin/flutter build apk --target-platform android-arm
      #
      #      - name: Upload files to a GitHub release
      #        uses: svenstaro/upload-release-action@1.0.1
      #        with:
      #          repo_token: ${{ secrets.GITHUB_TOKEN }}
      #          file: build/app/outputs/apk/release/app-release.apk
      #          asset_name: app-release-android-arm.apk
      #          tag: v0.5.3
      #          overwrite: true
      #
      #      # apk-arm64
      #      - name: Build APK android-arm64
      #        run: ./flutter/bin/flutter build apk --target-platform android-arm64
      #
      #      - name: Upload files to a GitHub release
      #        uses: svenstaro/upload-release-action@1.0.1
      #        with:
      #          repo_token: ${{ secrets.GITHUB_TOKEN }}
      #          file: build/app/outputs/apk/release/app-release.apk
      #          asset_name: app-release-android-arm64.apk
      #          tag: v0.5.3
      #          overwrite: true
      #
      #      # apk-x64
      #      - name: Build APK android-x64
      #        run: ./flutter/bin/flutter build apk --target-platform android-x64
      #
      #      - name: Upload files to a GitHub release
      #        uses: svenstaro/upload-release-action@1.0.1
      #        with:
      #          repo_token: ${{ secrets.GITHUB_TOKEN }}
      #          file: build/app/outputs/apk/release/app-release.apk
      #          asset_name: app-release-android-x64.apk
      #          tag: v0.5.3
      #          overwrite: true
      #
      #
      #
      #      # Build BUNDLE
      #      - name: Build Bundle
      #        run: ./flutter/bin/flutter build appbundle
      #
      #      - name: Upload files to a GitHub release
      #        uses: svenstaro/upload-release-action@1.0.1
      #        with:
      #          repo_token: ${{ secrets.GITHUB_TOKEN }}
      #          file: build/app/outputs/bundle/release/app-release.aab
      #          asset_name: app-release.aab
      #          tag: v0.5.3
      #          overwrite: true
      #
      #      # aab-arm
      #      - name: Build Bundle android-arm
      #        run: ./flutter/bin/flutter build appbundle --target-platform android-arm
      #
      #      - name: Upload files to a GitHub release
      #        uses: svenstaro/upload-release-action@1.0.1
      #        with:
      #          repo_token: ${{ secrets.GITHUB_TOKEN }}
      #          file: build/app/outputs/bundle/release/app-release.aab
      #          asset_name: app-release-android-arm.aab
      #          tag: v0.5.3
      #          overwrite: true
      #
      #      # aab-arm64
      #      - name: Build Bundle android-arm64
      #        run: ./flutter/bin/flutter build appbundle --target-platform android-arm64
      #
      #      - name: Upload files to a GitHub release
      #        uses: svenstaro/upload-release-action@1.0.1
      #        with:
      #          repo_token: ${{ secrets.GITHUB_TOKEN }}
      #          file: build/app/outputs/bundle/release/app-release.aab
      #          asset_name: app-release-android-arm64.aab
      #          tag: v0.5.3
      #          overwrite: true
      #
      #      # aab-x64
      #      - name: Build Bundle android-x64
      #        run: ./flutter/bin/flutter build appbundle --target-platform android-x64
      #
      #      - name: Upload files to a GitHub release
      #        uses: svenstaro/upload-release-action@1.0.1
      #        with:
      #          repo_token: ${{ secrets.GITHUB_TOKEN }}
      #          file: build/app/outputs/bundle/release/app-release.aab
      #          asset_name: app-release-android-x64.aab
      #          tag: v0.5.3
      #          overwrite: true


      # Build Desktop
      - name: Build macOS App
        run: ./flutter/bin/flutter build macos

      - name: Create DMG
        run: hdiutil create -format UDBZ -srcfolder build/macos/Build/Products/Release/passwall.app passwall.dmg

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@1.0.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/macos/Build/Products/Release/passwall.dmg
          asset_name: PassWall.app
          tag: v0.5.3
          overwrite: true
